# Generated by Django 4.2.7 on 2023-11-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='languages',
            field=models.ManyToManyField(to='demo.language'),
        ),
    ]
